### ISSUE TITLE
Grammar Issue on the "Contacting Organizations about Inaccessible Websites" Page

### ISSUE THREAD

**Issue by jfc3-dol** [w3c/wai-contacting-orgs#19]
I noticed a grammar issue while reading the "Contacting Organizations about Inaccessible Websites" page ( https://www.w3.org/WAI/teach-advocate/contact-inaccessible-websites/ ). I believe in the sentence below. The first word should be "The" instead of "They". The text is under the "Examples of problem descriptions:" section for "captions".

They videos are missing captions.

**Comment by remibetin** [comment]
Thanks @jfc3-dol! We have fixed this issue today. See https://www.w3.org/WAI/teach-advocate/contact-inaccessible-websites/
